### ISSUE TITLE
About Talkies dataset

### ISSUE THREAD

**Issue by Junhua-Liao** [SJTUwxz/LoCoNet_ASD#1]
May I kindly request if you could provide the preprocessing and testing codes for the Talkies dataset, please? I would really appreciate it if that's possible.

**Comment by SJTUwxz** [comment]
Hi Junhua, Thank you for your interest in our work! I'm so sorry for such late response! Sorry we don't have plans on releasing the training and testing pipeline on the Talkies dataset at the moment. I will keep you posted if we will release the training and testing codes later.

**Comment by Junhua-Liao** [comment]
Thanks for your reply. I have resolved the issue.
